### ISSUE TITLE
Components' Addition

### ISSUE THREAD

**Issue by Panagiotis-Kon** [5g-empower/empower-runtime#1]
1) In the section of the components, when i try to add a new one by giving for example: apps.mobilitymanager.mobilitymanager:ID (where ID is the id of an existing tenant),
it produces an error (Component not found and in console: jquery-2.1.4.min.js:4 POST http://127.0.0.1:8888/api/v1/components 404 (Not Found)).

2) If i try to add a new component by giving for example: 
apps.mobilitymanager.mobilitymanager --tenant_id=ID (where ID is the id of an existing tenant),
then there is no error message and the component seems to be loaded (INFO:core:Registering 'empower.apps.mobilitymanager.mobilitymanager'
INFO:core.app:Setting limit -30 dB
INFO:core.app:Setting control loop interval to 5000
), but it does not appear in the components list.

**Comment by rriggio** [comment]
I have probably fixed the issue in the last commit. Notice that now the tenant id is a regular module option. For example if you want to boot the controller with the mobility manager you shall now use:

`./empower-runtime.py apps.mobilitymanager.mobilitymanager --tenant_id=52313ecb-9d00-4b7d-b873-b55d3d9ada26`

Likewise, from the UI you must use:

`apps.mobilitymanager.mobilitymanager --tenant_id=52313ecb-9d00-4b7d-b873-b55d3d9ada26`

Notice also that global and tenant specific modules are now separated. When you log as root you can add both global and tenant specific modules. However tenant specific module will not appear when logged as root, instead you must log out and log in again as regular user to see them.

If you log in as regular user and then click on the components tab you must specify just the module name:

`apps.mobilitymanager.mobilitymanager`

**Comment by Panagiotis-Kon** [comment]
Now it works just fine.
