### ISSUE TITLE
New tornado version

### ISSUE THREAD

**Issue by joncnet** [5g-empower/empower-runtime#127]
The new tornado library broke the empower runtime: connections from vbs are accepted but not processed, no exceptions are raised.
Until empower updates to the latest tornado release, the fix is to install the latest compliant library version: 5.1.1

pip3 install tornado==5.1.1

https://pypi.org/project/tornado/4.1/#history

**Comment by rriggio** [comment]
Code has been ported to Tornado 6.0.0
