### ISSUE TITLE
Lvaps rates

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-runtime#16]
LVAPStats object has an attribute  
 ```
 # data structures
        self.rates = {}
```
each entry of rate list consist from:
1. rate
2. cur_prob
3. prob
4.flags

Can you explain me what do you mean with rates ? Are you reffering to lvap performance , bit rate?

**Comment by rriggio** [comment]
Hi,

those are the rate control statistic of the minstrel algorithm. Check this page:

https://wireless.wiki.kernel.org/en/developers/documentation/mac80211/ratecontrol/minstrel

Basically rate is the phy bitrate, e.g. for 11g is 6, 12, 18, 24, 36, 48 or 54. For an 11n network it would be the MCS 0-15. The others are the delivery probability in the last 500ms and prob is the EWMA delivery probability.
