### ISSUE TITLE
VBS Stats measurements

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/empower-runtime#19]
Hi,

Edit:
 I'm trying to trigger a vbs_cell_stats measurement in a VBS. In my application, after a vbs_up event. But the cells attribute of the VBS is always None. The same goes for the ue_rrc_meas which runs normally, but the ue.pcell_rsrp and ue.pcell_rsrq have the value None.
Also from various prints from the vbspconnection, the controller sends requests but never gets responses except from handle_ues_id_repl. The VBS and a UE are connected normally to the tenant. Any idea?

P.S.  I'm using the empower-runtime from the vbs branch.

Thank you in advance

**Comment by rriggio** [comment]
Him

we have made quite a bit of changes to the LTE part. For one we moved away from the OpenAirInterface and we have ported our agent technology to srsLTE. New tutorials for using 5G-EmPOWER with srsLTE are available in the wiki.

Regarding the measurements please give a look at the rrcmeasurementspoller.py application. This will show you how to collect RRC measurements.

For any other question please do not hesitate to post a message on the mailing list.

Cheers and happy 2018.

R.
