### ISSUE TITLE
WTPs' Connection to Controller

### ISSUE THREAD

**Issue by Panagiotis-Kon** [5g-empower/empower-runtime#2]
When a WTP tries to connect to the controller the following message appears in terminal:

INFO:core:Starting EmPOWER Runtime
INFO:core:Loading EmPOWER Runtime defaults
INFO:root:Importing module: empower.restserver.restserver
INFO:root:Importing module: empower.lvnfp.lvnfpserver
INFO:root:Importing module: empower.lvapp.lvappserver
INFO:root:Importing module: empower.energinoserver.energinoserver
INFO:root:Importing module: empower.lvap_stats.lvap_stats
INFO:root:Importing module: empower.events.wtpdown
INFO:root:Importing module: empower.events.wtpup
INFO:root:Importing module: empower.events.lvapleave
INFO:root:Importing module: empower.events.lvapjoin
INFO:root:Importing module: empower.counters.counters
INFO:root:Importing module: empower.maps.ucqm
INFO:root:Importing module: empower.maps.ncqm
INFO:root:Importing module: empower.triggers.rssi
INFO:root:Importing module: empower.triggers.summary
INFO:root:Importing module: empower.events.cppdown
INFO:root:Importing module: empower.events.cppup
INFO:root:Importing module: empower.events.lvnfjoin
INFO:root:Importing module: empower.events.lvnfleave
INFO:root:Importing module: empower.lvnf_ems.lvnf_get
INFO:root:Importing module: empower.lvnf_ems.lvnf_set
INFO:root:Importing module: empower.lvnf_stats.lvnf_stats
INFO:core:Registering 'empower.restserver.restserver'
INFO:restserver:REST Server available at 8888
INFO:core:Registering 'empower.lvnfp.lvnfpserver'
INFO:core.pnfpserver:LVNF Server available at 4422
INFO:core:Registering 'empower.lvapp.lvappserver'
INFO:core.pnfpserver:LVAP Server available at 4433
INFO:core:Registering 'empower.energinoserver.energinoserver'
INFO:energinoserver:Energino Server available at 5533
INFO:core:Registering 'empower.lvap_stats.lvap_stats'
INFO:core:Registering 'empower.events.wtpdown'
INFO:core:Registering 'empower.events.wtpup'
INFO:core:Registering 'empower.events.lvapleave'
INFO:core:Registering 'empower.events.lvapjoin'
INFO:core:Registering 'empower.counters.counters'
INFO:core:Registering 'empower.maps.ucqm'
INFO:core:Registering 'empower.maps.ncqm'
INFO:core:Registering 'empower.triggers.rssi'
INFO:core:Registering 'empower.triggers.summary'
INFO:core:Registering 'empower.events.cppdown'
INFO:core:Registering 'empower.events.cppup'
INFO:core:Registering 'empower.events.lvnfjoin'
INFO:core:Registering 'empower.events.lvnfleave'
INFO:core:Registering 'empower.lvnf_ems.lvnf_get'
INFO:core:Registering 'empower.lvnf_ems.lvnf_set'
INFO:core:Registering 'empower.lvnf_stats.lvnf_stats'
INFO:core.pnfpserver:Incoming connection from ('192.168.1.50', 56016)
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pkontopoulos/empower-runtime/empower/lvapp/lvappconnection.py", line 163, in _on_read
    self._trigger_message(hdr.type)
  File "/home/pkontopoulos/empower-runtime/empower/lvapp/lvappconnection.py", line 184, in _trigger_message
    handler(msg)
UnboundLocalError: local variable 'msg' referenced before assignment
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f35186ad268>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pkontopoulos/empower-runtime/empower/lvapp/lvappconnection.py", line 163, in _on_read
    self._trigger_message(hdr.type)
  File "/home/pkontopoulos/empower-runtime/empower/lvapp/lvappconnection.py", line 184, in _trigger_message
    handler(msg)
UnboundLocalError: local variable 'msg' referenced before assignment

**Comment by Panagiotis-Kon** [comment]
I have updated the comment above.

**Comment by rriggio** [comment]
I have tried to replicate this but without success. Are you sure you are running the latest version of the agent?

**Comment by Panagiotis-Kon** [comment]
Something was wrong with the agent image. Now it works without a problem.
