### ISSUE TITLE
Controller does not recognize WTPs

### ISSUE THREAD

**Issue by tomahawk291** [5g-empower/empower-runtime#20]
Dear, 
Your work is great and I am trying to do some experiment with 2 routers TPLINK1043ND using OpenWRT firmware you provided. But I got an issue when running the empower-runtime and adding WTPs. I already added controller IP address in  /etc/config/empower file but I had to manually set-controller address from openvswitch on routers. However, when I execute empower-runtime command, I got this:

INFO:core.pnfpserver: Incoming connection from ('192.168.250.1', 42215) and loop forever. May be I missed something? 

Thanks for your consideration.

**Comment by rriggio** [comment]
Hi,

I generally connect the rotuer to a network using the WAN interface. It
looks like you connected the machine running the controller to one of the
LAN interfaces of the router. This should be fine.

Do you mean that the empower-runtime prints a lot of those messages, i.e.
like it has gone in an infinite loop? This is strange. Could you confirm
that you are running the last version of agent and runtime. Could you copy
paste the entire output of the runtime.

R.

**Comment by tomahawk291** [comment]
Thank you for your quick reply, 
I connected the machine running controller to WAN interface of router, below is its information
![screenshot from 2017-08-16 10-07-59](https://user-images.githubusercontent.com/11684530/29343400-a9e68c0c-826b-11e7-8c4e-d0ade89fabcd.png)
And I had to set controller via ovs-vsctl switch (I am not sure why IP address in /etc/config/empower not working)
![screenshot from 2017-08-16 10-08-29](https://user-images.githubusercontent.com/11684530/29343426-e4738078-826b-11e7-8719-32b07b49da1e.png)
And last one is output of runtime screen
![screenshot from 2017-08-16 10-10-13](https://user-images.githubusercontent.com/11684530/29343434-f388c83e-826b-11e7-8d3f-d964b27fd1f7.png)
Thanks!!!

**Comment by rriggio** [comment]
can you send the output of ifconfing and the content of /etc/config/network
and /etc/config/empower

I assume that 192.168.250.1 is the machine running dhcp and running also
the empower-runtime, correct?

Are you using a network setup like this:

https://github.com/5g-empower/5g-empower.github.io/wiki/Network-setup#wtps

If not which are the differences?

R.

**Comment by tomahawk291** [comment]
Dear, 
This is my full setup. Did I go wrong something?
![screenshot from 2017-08-16 16-35-38](https://user-images.githubusercontent.com/11684530/29352284-1a2a57f2-82a1-11e7-8289-13b8a1dfd70b.png)

**Comment by rriggio** [comment]
can you send the ifconfig output and the files i asked you in the previous
message.

R.

**Comment by tomahawk291** [comment]
Sorry I missed them.
![screenshot from 2017-08-16 16-01-10](https://user-images.githubusercontent.com/11684530/29363572-828019e8-82cb-11e7-8cf7-06eb81325458.png)
![screenshot from 2017-08-16 16-00-44](https://user-images.githubusercontent.com/11684530/29363578-891f129a-82cb-11e7-86f3-4365a287847b.png)
Thanks!!!

**Comment by rriggio** [comment]
The LAN is on the 192.168.250.x subnet but you said that also the wan
itnerface is on the 192.168.250.x subnet. This is wrong. Either change the
lan subnet of the wan subnet.

R.

**Comment by tomahawk291** [comment]
Dear,
I changed a little bit in my experiment as you suggested.  However, I compared to your system, my router has 4 LAN and one WAN. I am just confuse that the problem is my WTPs does not receive the IP from dhcp server so it can't connect to my controller. Can you show me all your network design? Thank in advance.

**Comment by rriggio** [comment]
The WTP must be connected using its wan port to a network with a DHCP
server. The setup I am using is this one:

https://github.com/5g-empower/5g-empower.github.io/wiki/Network-setup#wtps

The network configuration of the WTP must be modified in order to bridge
the WAN port (typically the eth0, but not always with the br-ovs bridge.
Unfortunately, it is hard to debug this without having the router in the
lab. You need some basic networking skills and you need to read the OpenWRT
wiki in order to know how the ports on your router are configured.

Foe example in this repo:

https://github.com/5g-empower/empower-configs

I have the config files for the routers I use in the lab.

R.
