### ISSUE TITLE
Interference

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-runtime#21]
I can find classfunction _handle_interference_map but nowhere interference_map application.
Are you planning to create it again?

**Comment by rriggio** [comment]
the primitives for channel quality are the ones used in this app:

https://github.com/5g-empower/empower-runtime/blob/master/empower/apps/rssitracker/rssitracker.py

where did you find those methods?

R.

**Comment by Giwrgosyea** [comment]
lvapconnection.py line 754

**Comment by rriggio** [comment]
good catch. indeed is a dead function. all that has been integrated in the
channel quality map

**Comment by Giwrgosyea** [comment]
Beside rssitracker , is there any way to specify the interference ?

**Comment by rriggio** [comment]
rssitracker is not used to specify interference. it is an example about how to use the UCQM function. The ucqm function collects RSSI measurements from one WTP, see here:

https://github.com/5g-empower/5g-empower.github.io/wiki/Python-Wi-Fi-API-documentation

Please use the mailing list for support request. The issues are supposed to be used for bugs or feature request.
