### ISSUE TITLE
Channel Busyness Measurement Value

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/empower-runtime#22]
Hi Riggio,

I'm trying to figure out what is the value that the busyness measurement returns from the WTP? Can you please clarify what the value represents.

Thank you

**Comment by rriggio** [comment]
please use the mailing list for support questions. the issue tracker is for bug and feature requests.

the busyness is the percentage of time the medium is busy for transmissions. It is an estimation because it considers only sniffed frames and their rate.
