### ISSUE TITLE
Mobility Manager App - RSSI problem

### ISSUE THREAD

**Issue by Panagiotis-Kon** [5g-empower/empower-runtime#3]
In the web interface of the mobility manager app the RSSI value always shows null, although there is an active connection between the LVAP and the WTP.
More specifically, from the following line **ucqm = wtps[wtp].supports[block].ucqm[lvap_addr]** (in mobilitymanager.lib.js), the variable ucqm seems to be undefined or empty as the javascript console indicates. Also the ucqm object, inside the json response, appears to be empty.

**Comment by rriggio** [comment]
Fixed. Basically, when loading and app from the webdashboard or from the empower-manager cli the wtpup events were not generated. Without the wtpup event the UCQM could not be created. Now it should work as expected. I'll wait for your confirmation to close the issue.
