### ISSUE TITLE
QoS, Network Slices: Configuration issue

### ISSUE THREAD

**Issue by kewinrausch** [5g-empower/empower-runtime#92]
The Runtime seems to not allow edit the Slice details if a slice if created not with the button but with database contents (from the start). This work for the default slice and non-default slices.

**Repeat with:** Create a Slice different from the default, reboot the Runtime and then try to modify the slice details/setting. The usual window does not show up and clicking does not have any effects.

![feature](https://user-images.githubusercontent.com/8994703/47483131-c46c4c00-d838-11e8-9e70-58dbf6979f95.png)

**Comment by kewinrausch** [comment]
Quick update: this does not always happens.
I'm still trying to find a way to make it repeatable.

**Comment by rriggio** [comment]
Do you know if the same happens if you use directly the REST interface?

**Comment by kewinrausch** [comment]
I will need to test this. Will be back with an update soon.

**Comment by kewinrausch** [comment]
Last modifications seems to have resolved the problem.. closing the issue
